- name: Wait for app to start
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 5000
    delay: 5
    timeout: 30

- name: Check health
  uri:
    url: "http://{{ inventory_hostname }}:5000/health"
    status_code: 200

