[blue_nodes]
blue1 ansible_connection=docker
blue2 ansible_connection=docker

[green_nodes]
green1 ansible_connection=docker
green2 ansible_connection=docker

[loadbalancer]
loadbalancer ansible_connection=docker
